"""
inject_fictitious_compounds.py
-------------------------------
Injects one fictitious compound into `raw_label_text` per record.

The fictitious compound is generated by a grammar that mirrors the exact
naming conventions of real INS / Codex Alimentarius compounds:

  Pattern A  [cation] [acid-base]-ate
             e.g. "dipotassium fumarate", "calcium erythorbate"
             mirrors: sodium benzoate (211), potassium sorbate (202)

  Pattern B  [modifier]-[base] [acid]
             e.g. "dihydroxypropyl succinic acid", "hydroxyethyl tartaric acid"
             mirrors: glucono delta-lactone (575), diacetyl tartaric acid (472e)

  Pattern C  [cation] [base]oyl [end]
             e.g. "magnesium stearoyl fumarate", "sodium palmitoyl lactylate"
             mirrors: sodium stearoyl lactylate (481), calcium stearoyl lactylate (482)

  Pattern D  [acid] esters of [glyceride-base]
             e.g. "succinic acid esters of mono- and diglycerides of fatty acids"
             mirrors: acetic acid esters of mono- and diglycerides (472a),
                      lactic acid esters of mono- and diglycerides (472b)

  Pattern E  [modifier][polymer-base] [treatment]
             e.g. "propylated distarch fumarate", "butyrylated hydroxypropyl starch"
             mirrors: acetylated distarch adipate (1422),
                      hydroxypropyl distarch phosphate (1442)

  Pattern F  poly[base]-[number]
             e.g. "polysorbate 45", "polysorbate 35"
             mirrors: polysorbate 20 (432), polysorbate 60 (435), polysorbate 80 (433)

  Pattern G  [multiplier][cation] [base]ate
             e.g. "dipotassium succinate", "tricalcium malate"
             mirrors: disodium guanylate (627), disodium inosinate (631)

  Pattern H  [hydroxy/alkyl]-[base]cellulose
             e.g. "hydroxybutyl methylcellulose", "ethylhydroxypropyl cellulose"
             mirrors: hydroxypropyl methylcellulose (464),
                      sodium carboxymethylcellulose (466)

Each generated compound:
  - sounds like a genuine INS name (same morpheme vocabulary, same grammar)
  - is assigned a plausible fictitious INS number (gap in real sequence)
  - is injected in authentic Indian label format:
      FUNCTIONAL CLASS [NAME (INS XXXX)]        -- most common
      FUNCTIONAL CLASS (NAME, INS XXXX)         -- common variant
      NAME (INS XXXX) [FUNCTIONAL CLASS]        -- less common

Output adds:
  "fictitious_compound_injected": true | false
  "fictitious_compound_changes": {
      "ins_code":         fictitious INS number string
      "compound_name":    generated name
      "functional_class": FSSAI class title
      "pattern":          A-H (which naming grammar was used)
      "char_index":       position in modified raw_label_text
      "explanation":      human-readable note
  }

Usage:
    python inject_fictitious_compounds.py <input.jsonl>

Output:
    <stem>_fictitious_compounds.jsonl
"""

import copy
import json
import os
import random
import re
import sys

# ---------------------------------------------------------------------------
# Grammar building blocks — all morphemes drawn from real INS compound names
# ---------------------------------------------------------------------------

CATIONS = [
    "sodium",
    "potassium",
    "calcium",
    "magnesium",
    "ammonium",
    "dipotassium",
    "disodium",
    "tricalcium",
]
ACID_BASES = [
    "fumarate",
    "succinate",
    "adipate",
    "malonate",
    "glutarate",
    "erythorbate",
    "glucuronate",
    "lactobionate",
    "tartrate",
    "propionate",
    "butyrate",
    "valerate",
    "isovalerate",
    "itaconate",
    "maleate",
    "oxalate",
    "pimelate",
]
ACID_NAMES = [
    "succinic",
    "glutaric",
    "adipic",
    "malonic",
    "itaconic",
    "fumaric",
    "suberic",
    "glucuronic",
    "pyruvic",
    "levulinic",
    "caprylic",
    "capric",
    "lauric",
]
ACID_MODIFIERS = [
    "dihydroxy",
    "hydroxy",
    "diacetyl",
    "triacetyl",
    "methyl",
    "dimethyl",
    "ethyl",
    "propyl",
]
ACYL_BASES = [
    "stearoyl",
    "palmitoyl",
    "oleoyl",
    "lauroyl",
    "myristoyl",
    "behenoyl",
    "erucamidyl",
]
ACYL_ENDS = ["lactylate", "fumarate", "succinate", "tartrate", "phosphate", "citrate"]
ESTER_ACIDS = [
    "succinic acid",
    "glutaric acid",
    "adipic acid",
    "fumaric acid",
    "itaconic acid",
    "suberic acid",
    "malic acid",
    "gluconic acid",
    "pyruvic acid",
]
POLYMER_MODS = [
    "propylated",
    "butyrylated",
    "succinylated",
    "phosphorylated",
    "carboxymethylated",
    "octenylated",
]
POLYMER_BASES = ["distarch", "tristarch", "amylose", "amylopectin"]
POLYMER_ENDS = [
    "fumarate",
    "succinate",
    "glutarate",
    "maleate",
    "itaconate",
    "adipate",
    "pimelate",
]
POLY_NUMBERS = [25, 35, 45, 55, 85, 120]  # real ones: 20,40,60,65,80
MULTI_CATIONS = ["dipotassium", "disodium", "tricalcium", "diammonium", "trimagnesium"]
MULTI_BASES = [
    "succinate",
    "fumarate",
    "glutarate",
    "malonate",
    "itaconate",
    "adipate",
    "gluconate",
    "tartrate",
    "phosphonate",
    "erythorbate",
]
CELLU_PREFIX1 = [
    "hydroxybutyl",
    "hydroxyethyl",
    "carboxyethyl",
    "sulfoethyl",
    "phosphoethyl",
]
CELLU_PREFIX2 = ["methyl", "ethyl", "propyl", "butyl"]

# Fictitious INS numbers — gaps in the real INS sequence that are unassigned
# (verified against the complete Wikipedia list)
FICTITIOUS_INS_NUMBERS = [
    "106",
    "108",
    "109",
    "113",
    "114",
    "115",
    "116",
    "117",
    "118",
    "119",
    "136",
    "137",
    "138",
    "143b",
    "145",
    "146",
    "147",
    "148",
    "149",
    "156",
    "157",
    "158",
    "159",
    "160g",
    "160h",
    "161k",
    "164(i)",
    "164(ii)",
    "167",
    "168",
    "169",
    "204",
    "205",
    "206",
    "207",
    "208",
    "243",
    "244",
    "245",
    "246",
    "253",
    "254",
    "255",
    "267",
    "268",
    "271",
    "272",
    "273",
    "274",
    "286",
    "287",
    "288",
    "289",
    "291",
    "292",
    "293",
    "294",
    "295",
    "303(i)",
    "303(ii)",
    "305",
    "306",
    "313",
    "314",
    "323",
    "324",
    "328(i)",
    "329(i)",
    "344(i)",
    "346",
    "347",
    "348",
    "358",
    "360",
    "361",
    "362",
    "369",
    "371",
    "372",
    "373",
    "374",
    "382",
    "383",
    "392",
    "393",
    "394",
    "395",
    "396",
    "397",
    "398",
    "408",
    "411",
    "419",
    "423",
    "424",
    "425(i)",
    "426",
    "427",
    "437",
    "438",
    "439",
    "443(i)",
    "446",
    "447",
    "448",
    "453",
    "454",
    "455",
    "456",
    "457",
    "458",
    "461(i)",
    "462",
    "467",
    "472g",
    "472h",
    "473(i)",
    "479a",
    "483(i)",
    "484",
    "485",
    "486",
    "487",
    "488",
    "489",
    "496",
    "497",
    "498",
    "499",
    "506",
    "532",
    "533",
    "534",
    "543",
    "546",
    "547",
    "548",
    "549",
    "556(i)",
    "557",
    "561",
    "562",
    "563",
    "564",
    "565",
    "566",
    "571",
    "572",
    "573",
    "574",
    "580",
    "581",
    "582",
    "583",
    "584",
    "586",
    "587",
    "614",
    "615",
    "616",
    "617",
    "618",
    "619",
    "622(i)",
    "623(i)",
    "624(i)",
    "625(i)",
    "642",
    "643",
    "644",
    "645",
    "646",
    "647",
    "648",
    "649",
    "901(i)",
    "902(i)",
    "906",
    "908",
    "909",
    "910",
    "911",
    "921",
    "922",
    "923",
    "929",
    "930",
    "931",
    "944",
    "945",
    "946",
    "947",
    "948",
    "949",
    "956(i)",
    "957(i)",
    "958",
    "961",
    "962",
    "963",
    "964",
    "968",
    "969",
    "970",
    "971",
    "972",
    "1002",
    "1003",
    "1004",
    "1005",
    "1006",
    "1101(iv)",
    "1103(i)",
    "1106",
    "1107",
    "1108",
    "1109",
    "1201(i)",
    "1203",
    "1204",
    "1205",
    "1406",
    "1407",
    "1408",
    "1409",
    "1411",
    "1415",
    "1416",
    "1417",
    "1418",
    "1419",
    "1421",
    "1423",
    "1424",
    "1425",
    "1426",
    "1427",
    "1428",
    "1429",
    "1441",
    "1443",
    "1444",
    "1445",
    "1446",
    "1447",
    "1448",
    "1449",
    "1451(i)",
    "1452",
    "1453",
    "1454",
    "1455",
    "1506",
    "1507",
    "1508",
    "1509",
    "1519",
    "1522",
    "1523",
    "1524",
]

# FSSAI functional class titles
FUNCTIONAL_CLASSES = [
    "EMULSIFIER",
    "STABILISER",
    "THICKENER",
    "HUMECTANT",
    "ACIDITY REGULATOR",
    "SEQUESTRANT",
    "FIRMING AGENT",
    "ANTICAKING AGENT",
    "COLOUR RETENTION AGENT",
    "ANTIOXIDANT",
    "GLAZING AGENT",
    "MODIFIED STARCH",
    "FLOUR TREATMENT AGENT",
    "FOAMING AGENT",
    "CARRIER",
]

# Functional class most appropriate for each pattern
PATTERN_CLASS_MAP = {
    "A": ["EMULSIFIER", "STABILISER", "ACIDITY REGULATOR", "SEQUESTRANT"],
    "B": ["ACIDITY REGULATOR", "ANTIOXIDANT", "SEQUESTRANT", "FIRMING AGENT"],
    "C": ["EMULSIFIER", "STABILISER", "FLOUR TREATMENT AGENT"],
    "D": ["EMULSIFIER", "STABILISER", "THICKENER"],
    "E": ["MODIFIED STARCH", "THICKENER", "STABILISER"],
    "F": ["EMULSIFIER", "STABILISER", "HUMECTANT"],
    "G": ["ACIDITY REGULATOR", "SEQUESTRANT", "FLAVOUR ENHANCER"],
    "H": ["THICKENER", "STABILISER", "EMULSIFIER", "HUMECTANT"],
}

# ---------------------------------------------------------------------------
# Name generators — one per pattern
# ---------------------------------------------------------------------------


def _gen_A(rng):
    """[cation] [acid-base]-ate  — mirrors INS 202, 211, 282"""
    cation = rng.choice(["sodium", "potassium", "calcium", "magnesium", "ammonium"])
    base = rng.choice(ACID_BASES)
    return f"{cation} {base}"


def _gen_B(rng):
    """[modifier]-[base] [acid]  — mirrors INS 472e (diacetyl tartaric acid)"""
    mod = rng.choice(ACID_MODIFIERS)
    acid = rng.choice(ACID_NAMES)
    return f"{mod} {acid} acid"


def _gen_C(rng):
    """[cation] [acyl]oyl [end]  — mirrors INS 481, 482"""
    cation = rng.choice(["sodium", "potassium", "calcium", "magnesium"])
    acyl = rng.choice(ACYL_BASES)
    end = rng.choice(ACYL_ENDS)
    return f"{cation} {acyl} {end}"


def _gen_D(rng):
    """[acid] esters of mono- and diglycerides  — mirrors INS 472a-f"""
    acid = rng.choice(ESTER_ACIDS)
    return f"{acid} esters of mono- and diglycerides of fatty acids"


def _gen_E(rng):
    """[modifier][polymer] [end]  — mirrors INS 1422, 1442"""
    mod = rng.choice(POLYMER_MODS)
    base = rng.choice(POLYMER_BASES)
    end = rng.choice(POLYMER_ENDS)
    return f"{mod} {base} {end}"


def _gen_F(rng):
    """polysorbate [N]  — mirrors INS 432, 435, 436, 433"""
    n = rng.choice(POLY_NUMBERS)
    return f"polysorbate {n}"


def _gen_G(rng):
    """[di/tri][cation] [base]  — mirrors INS 627, 631, 635"""
    cation = rng.choice(MULTI_CATIONS)
    base = rng.choice(MULTI_BASES)
    return f"{cation} {base}"


def _gen_H(rng):
    """[hydroxy/alkyl]-[X]cellulose  — mirrors INS 464, 466"""
    p1 = rng.choice(CELLU_PREFIX1)
    p2 = rng.choice(CELLU_PREFIX2)
    # Vary structure: sometimes [p1][p2]cellulose, sometimes [p1] [p2]cellulose
    if rng.random() < 0.5:
        return f"{p1} {p2}cellulose"
    else:
        return f"{p1}{p2}cellulose"


PATTERN_GENERATORS = {
    "A": _gen_A,
    "B": _gen_B,
    "C": _gen_C,
    "D": _gen_D,
    "E": _gen_E,
    "F": _gen_F,
    "G": _gen_G,
    "H": _gen_H,
}

# ---------------------------------------------------------------------------
# Product category detection (to weight pattern selection sensibly)
# ---------------------------------------------------------------------------

CATEGORY_SIGNALS = {
    "biscuit": [
        "biscuit",
        "maida",
        "wheat flour",
        "invert syrup",
        "raising agent",
        "shortening",
    ],
    "snack": ["potato", "corn meal", "rice meal", "seasoning", "chilli", "extruded"],
    "beverage": [
        "carbonated water",
        "fruit juice",
        "mango pulp",
        "caffeine",
        "taurine",
    ],
    "noodle": ["noodle", "pasta", "wheat gluten", "semolina"],
    "sauce": ["tomato paste", "vinegar", "ketchup", "onion powder"],
    "dairy": ["milk", "curd", "butter", "cheese", "whey"],
    "confection": ["cocoa", "chocolate", "glucose syrup", "candy"],
}

# Pattern weights per category (keys are patterns A-H)
CATEGORY_PATTERN_WEIGHTS = {
    "biscuit": {"A": 1, "B": 1, "C": 3, "D": 3, "E": 3, "F": 1, "G": 1, "H": 2},
    "snack": {"A": 2, "B": 2, "C": 2, "D": 2, "E": 3, "F": 1, "G": 2, "H": 1},
    "beverage": {"A": 3, "B": 2, "C": 1, "D": 1, "E": 1, "F": 2, "G": 3, "H": 2},
    "noodle": {"A": 2, "B": 1, "C": 3, "D": 3, "E": 3, "F": 1, "G": 1, "H": 2},
    "sauce": {"A": 2, "B": 2, "C": 2, "D": 2, "E": 2, "F": 1, "G": 2, "H": 2},
    "dairy": {"A": 2, "B": 2, "C": 3, "D": 2, "E": 1, "F": 2, "G": 2, "H": 3},
    "confection": {"A": 1, "B": 1, "C": 3, "D": 3, "E": 2, "F": 2, "G": 1, "H": 2},
    "generic": {"A": 2, "B": 2, "C": 2, "D": 2, "E": 2, "F": 1, "G": 2, "H": 2},
}


def detect_category(text_lower):
    for cat, signals in CATEGORY_SIGNALS.items():
        if any(s in text_lower for s in signals):
            return cat
    return "generic"


# ---------------------------------------------------------------------------
# Label injection formats
# ---------------------------------------------------------------------------


def _inject_into_label(label_text, compound_str):
    """Splice before CONTAINS / ADDED FLAVOUR / ADDED COLOUR, else append."""
    m = re.search(
        r"(CONTAINS\b|Contains\b|ADDED FLAVOUR|ADDED COLOR|ADDED COLOUR|"
        r"PERMITTED NATURAL|PERMITTED SYNTHETIC|Numbers in brackets)",
        label_text,
        re.IGNORECASE,
    )
    if m:
        pos = m.start()
        before = label_text[:pos].rstrip(", \r\n")
        after = label_text[pos:]
        new = before + ", " + compound_str + " " + after
        return new, len(before) + 2
    else:
        stripped = label_text.rstrip(". \r\n")
        new = stripped + ", " + compound_str
        return new, len(stripped) + 2


def _build_label_fragment(compound_name, ins_code, func_class, rng):
    """
    Build the full label string in one of three authentic Indian formats:

    Format 1 (most common):  FUNCTIONAL CLASS [NAME (INS XXXX)]
    Format 2 (common):       FUNCTIONAL CLASS (NAME, INS XXXX)
    Format 3 (less common):  NAME (INS XXXX) [FUNCTIONAL CLASS]
    """
    fmt = rng.choices([1, 2, 3], weights=[45, 35, 20])[0]
    display = compound_name.upper()
    if fmt == 1:
        return f"{func_class} [{display} (INS {ins_code})]"
    elif fmt == 2:
        return f"{func_class} ({display}, INS {ins_code})"
    else:
        return f"{display} (INS {ins_code}) [{func_class}]"


# ---------------------------------------------------------------------------
# Core
# ---------------------------------------------------------------------------


def generate_compound(category, rng, used_ins):
    """
    Pick a pattern appropriate for the category, generate a name,
    assign a fictitious INS number not already used this file.
    Returns (compound_name, ins_code, pattern, func_class).
    """
    weights_dict = CATEGORY_PATTERN_WEIGHTS.get(
        category, CATEGORY_PATTERN_WEIGHTS["generic"]
    )
    patterns = sorted(weights_dict.keys())
    weights = [weights_dict[p] for p in patterns]
    pattern = rng.choices(patterns, weights=weights)[0]

    compound_name = PATTERN_GENERATORS[pattern](rng)

    # Pick a fictitious INS number not used this run
    available = sorted(set(FICTITIOUS_INS_NUMBERS) - used_ins)
    ins_code = rng.choice(available)
    used_ins.add(ins_code)

    # Pick a contextually appropriate functional class
    func_class = rng.choice(PATTERN_CLASS_MAP[pattern])

    return compound_name, ins_code, pattern, func_class


def process_record(record, rng, used_ins):
    rec = copy.deepcopy(record)
    rec.pop("fictitious_compound_injected", None)
    rec.pop("fictitious_compound_changes", None)

    label_text = rec.get("raw_label_text", "").strip()
    if len(label_text) < 10:
        rec["fictitious_compound_injected"] = False
        rec["fictitious_compound_changes"] = {
            "ins_code": None,
            "compound_name": None,
            "functional_class": None,
            "pattern": None,
            "char_index": None,
            "explanation": "Label text too short to inject a compound.",
        }
        return rec

    category = detect_category(label_text.lower())
    compound_name, ins_code, pattern, func_class = generate_compound(
        category, rng, used_ins
    )

    fragment = _build_label_fragment(compound_name, ins_code, func_class, rng)
    new_text, char_index = _inject_into_label(label_text, fragment)
    rec["raw_label_text"] = new_text

    rec["fictitious_compound_injected"] = True
    rec["fictitious_compound_changes"] = {
        "ins_code": ins_code,
        "compound_name": compound_name,
        "full_fragment": fragment,
        "functional_class": func_class,
        "naming_pattern": pattern,
        "detected_category": category,
        "char_index": char_index,
        "explanation": (
            f"Fictitious compound '{compound_name}' (INS {ins_code}) injected "
            f"using naming Pattern {pattern}, which mirrors real INS compound "
            f"grammar. The INS number {ins_code} is unassigned in the official "
            f"Codex Alimentarius list. Detected product category: '{category}'."
        ),
    }
    return rec


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def process_file(input_path, seed=42):
    records = []
    with open(input_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                records.append(json.loads(line))

    print(f"Loaded {len(records)} records from '{input_path}'")

    rng = random.Random(seed)
    used_ins = set()  # track across records so no two records share an INS number

    stem, _ = os.path.splitext(input_path)
    out_path = stem + "_fictitious_compounds.jsonl"

    injected = 0
    skipped = 0
    pattern_counts = {}

    with open(out_path, "w", encoding="utf-8") as out_f:
        for rec in records:
            processed = process_record(rec, rng, used_ins)
            out_f.write(json.dumps(processed, ensure_ascii=False) + "\n")
            if processed["fictitious_compound_injected"]:
                injected += 1
                p = processed["fictitious_compound_changes"]["naming_pattern"]
                pattern_counts[p] = pattern_counts.get(p, 0) + 1
            else:
                skipped += 1

    print(f"  Compounds injected  : {injected}")
    print(f"  Skipped (too short) : {skipped}")
    print(f"  Pattern distribution: {dict(sorted(pattern_counts.items()))}")
    print(f"  Output: {out_path}")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python inject_fictitious_compounds.py <input.jsonl>")
        sys.exit(1)
    path = sys.argv[1]
    if not os.path.isfile(path):
        print(f"File not found: {path}")
        sys.exit(1)
    process_file(path)
